conditions:
    -
        key: !ruby/symbol edition
        value: !ruby/symbol desc
    -
        key: !ruby/symbol author
        value: !ruby/symbol desc
    -
        key: !ruby/symbol title
        value: !ruby/symbol asc
        
books:
    -
        title: 'Java How to Program'
        author: 'Deitel & Deitel'
        edition: '2007'
    -
        title: 'Patterns of Enterprise Application Architecture'
        author: 'Martin Fowler'
        edition: '2002'
    -
        title: 'Head First Design Patterns'
        author: 'Elisabeth Freeman'
        edition: '2004'
    -
        title: 'Internet & World Wide Web: How to Program'
        author: 'Deitel & Deitel'
        edition: '2007'