# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sorting_service_books"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Douglas Petronilio"]
  s.date = "2014-06-02"
  s.description = "Gem to sorting a collection of the books by any atributes."
  s.email = "dougpetronilio@gmail.com"
  s.executables = ["VERSION", "config_one_condition.yml", "config_three_conditions.yml", "config_two_conditions.yml", "config_without_condition.yml", "service_books.rb", "test.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/VERSION",
    "bin/config_one_condition.yml",
    "bin/config_three_conditions.yml",
    "bin/config_two_conditions.yml",
    "bin/config_without_condition.yml",
    "bin/service_books.rb",
    "bin/test.rb",
    "config_one_condition.yml",
    "config_three_conditions.yml",
    "config_two_conditions.yml",
    "config_without_condition.yml",
    "lib/sorting_service_books.rb",
    "lib/sorting_service_books/book.rb",
    "lib/sorting_service_books/client.rb",
    "lib/sorting_service_books/load_config.rb",
    "lib/sorting_service_books/order.rb",
    "lib/sorting_service_books/ordering_exception.rb",
    "lib/sorting_service_books/sort_books.rb",
    "lib/sorting_service_books/version.rb",
    "sorting_service_books.gemspec",
    "spec/book_spec.rb",
    "spec/client_spec.rb",
    "spec/load_config_spec.rb",
    "spec/order_spec.rb",
    "spec/sort_books_spec.rb",
    "spec/sorting_service_books_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dougpetronilio/sorting_service_books"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Gem to sorting a collection of the books."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

